In [1]:
import numpy as np
import pandas as pd
import os
import warnings
from sklearn.base import BaseEstimator, TransformerMixin
import warnings
import wandb

In [2]:
warnings.filterwarnings('ignore')

In [3]:
# Login to Weights & Biases
wandb.login()

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: hangtn13-ssc-national-economics-university (use `wandb login --relogin` to force relogin)

True

In [4]:
input_artifact="Bank-Marketing/raw_data.csv:latest"
artifact_name="preprocessed_data.csv"
artifact_type="clean_data"
artifact_description="Data after preprocessing"

In [6]:
# Create a new job_type
run = wandb.init(project="Bank-Marketing", job_type="process_data")

VBox(children=(Label(value='0.000 MB of 0.000 MB uploaded (0.000 MB deduped)\r'), FloatProgress(value=1.0, max…

In [7]:
run = wandb.init(project='Bank-Marketing', job_type='process_data')
artifact = run.use_artifact('hangtn13-ssc-national-economics-university/Bank-Marketing/raw_data:latest', type='dataset')
artifact_dir = artifact.download()
df= pd.read_csv(os.path.join(artifact_dir, 'raw_data.csv'))

VBox(children=(Label(value='0.000 MB of 0.000 MB uploaded (0.000 MB deduped)\r'), FloatProgress(value=1.0, max…

# **LOADING DATA**

## Data Description

Citation Request:
  This dataset is publicly available for research. The details are described in [Moro et al., 2014].
  Please include this citation if you plan to use this database:

  [Moro et al., 2014] S. Moro, P. Cortez and P. Rita. A Data-Driven Approach to Predict the Success of Bank Telemarketing. Decision Support Systems, In press, http://dx.doi.org/10.1016/j.dss.2014.03.001

  Available at: [pdf] http://dx.doi.org/10.1016/j.dss.2014.03.001
                [bib] http://www3.dsi.uminho.pt/pcortez/bib/2014-dss.txt

**1. Title: Bank Marketing (with social/economic context)**

**2. Sources**
   Created by: Sérgio Moro (ISCTE-IUL), Paulo Cortez (Univ. Minho) and Paulo Rita (ISCTE-IUL) @ 2014
   
**3. Past Usage:**

  The full dataset (bank-additional-full.csv) was described and analyzed in:

  S. Moro, P. Cortez and P. Rita. A Data-Driven Approach to Predict the Success of Bank Telemarketing. Decision Support Systems (2014), doi:10.1016/j.dss.2014.03.001.

**4. Relevant Information:**

   This dataset is based on "Bank Marketing" UCI dataset (please check the description at: http://archive.ics.uci.edu/ml/datasets/Bank+Marketing).
   The data is enriched by the addition of five new social and economic features/attributes (national wide indicators from a ~10M population country), published by the Banco de Portugal and publicly available at: https://www.bportugal.pt/estatisticasweb.
   This dataset is almost identical to the one used in [Moro et al., 2014] (it does not include all attributes due to privacy concerns).
   Using the rminer package and R tool (http://cran.r-project.org/web/packages/rminer/), we found that the addition of the five new social and economic attributes (made available here) lead to substantial improvement in the prediction of a success, even when the duration of the call is not included. Note: the file can be read in R using: d=read.table("bank-additional-full.csv",header=TRUE,sep=";")
   
   The zip file includes two datasets:
      1) bank-additional-full.csv with all examples, ordered by date (from May 2008 to November 2010).
      2) bank-additional.csv with 10% of the examples (4119), randomly selected from bank-additional-full.csv.
   The smallest dataset is provided to test more computationally demanding machine learning algorithms (e.g., SVM).

   The binary classification goal is to predict if the client will subscribe a bank term deposit (variable y).

**5. Number of Instances:** 41188 for bank-additional-full.csv

**6. Number of Attributes:** 20 + output attribute.

**7. Attribute information:**

   For more information, read [Moro et al., 2014].

   Input variables:
   **bank client data:**

   1 - age (numeric)

   2 - job : type of job (categorical: "admin.","blue-collar","entrepreneur","housemaid","management","retired","self-employed","services","student","technician","unemployed","unknown")

   3 - marital : marital status (categorical: "divorced","married","single","unknown"; note: "divorced" means divorced or widowed)

   4 - education (categorical: "basic.4y","basic.6y","basic.9y","high.school","illiterate","professional.course","university.degree","unknown")

   5 - default: has credit in default? (categorical: "no","yes","unknown")

   6 - housing: has housing loan? (categorical: "no","yes","unknown")

   7 - loan: has personal loan? (categorical: "no","yes","unknown")
**related with the last contact of the current campaign:**
   8 - contact: contact communication type (categorical: "cellular","telephone")

   9 - month: last contact month of year (categorical: "jan", "feb", "mar", ..., "nov", "dec")

  10 - day_of_week: last contact day of the week (categorical: "mon","tue","wed","thu","fri")

  11 - duration: last contact duration, in seconds (numeric). Important note:  this attribute highly affects the output target (e.g., if duration=0 then y="no"). Yet, the duration is not known before a call is performed. Also, after the end of the call y is obviously known. Thus, this input should only be included for benchmark purposes and should be discarded if the intention is to have a realistic predictive model.

**other attributes:**
  12 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)

  13 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric; 999 means client was not previously contacted)

  14 - previous: number of contacts performed before this campaign and for this client (numeric)

  15 - poutcome: outcome of the previous marketing campaign (categorical: "failure","nonexistent","success")

**social and economic context attributes**

  16 - emp.var.rate: employment variation rate - quarterly indicator (numeric)

  17 - cons.price.idx: consumer price index - monthly indicator (numeric)

  18 - cons.conf.idx: consumer confidence index - monthly indicator (numeric)     

  19 - euribor3m: euribor 3 month rate - daily indicator (numeric)
  
  20 - nr.employed: number of employees - quarterly indicator (numeric)

**Output variable (desired target):**
  21 - y - has the client subscribed a term deposit? (binary: "yes","no")

**8. Missing Attribute Values:** There are several missing values in some categorical attributes, all coded with the "unknown" label. These missing values can be treated as a possible class label or using deletion or imputation techniques.

In [8]:
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp_var_rate    41188 non-null  float64
 16  cons_price_idx  41188 non-null  float64
 17  cons_conf_idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr_employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [10]:
df.describe()

,age,duration,campaign,pdays,previous,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed
count,41188.00000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000
mean,40.02406,258.285010,2.567593,962.475454,0.172963,0.081886,93.575664,-40.502600,3.621291,5167.035911
std,10.42125,259.279249,2.770014,186.910907,0.494901,1.570960,0.578840,4.628198,1.734447,72.251528
min,17.00000,0.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.00000,102.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.00000,180.000000,2.000000,999.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000
75%,47.00000,319.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,98.00000,4918.000000,56.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

In [11]:
df.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp_var_rate      0
cons_price_idx    0
cons_conf_idx     0
euribor3m         0
nr_employed       0
y                 0
dtype: int64

In [12]:
df.duplicated().sum()

12

In [13]:
df.drop_duplicates(inplace=True)

### Removing the 'duration' Column – Reasoning

The **'duration'** column represents the duration of the **last call** and is only known after the call has ended. At that point, the **subscription result (y)** (whether the customer subscribed or not) is already determined. Furthermore, when **duration = 0**, the result is always **y = 'no'**.

This creates a risk of **data leakage**, as the feature **'duration'** could potentially reveal information about the target variable **'y'** (subscription result). Removing this column helps ensure the integrity of the model by preventing the model from unintentionally using future information to predict outcomes.

**Insight:**  
By removing the **'duration'** column, we eliminate the risk of data leakage and ensure that the model is based solely on information available before the outcome is known.

In [14]:
df.drop(columns='duration', inplace=True)

# **DATA CLEANING**

In [15]:
df.head(10)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
5,45,services,married,basic.9y,unknown,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
6,59,admin.,married,professional.course,no,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
7,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
8,24,technician,single,professional.course,no,yes,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
9,25,services,single,high.school,no,yes,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

## Create a pipeline for handling text-related errors

- **JobAdminCleaner** (`clean_job_admin`): Fix the input error where "admin." is mistakenly entered as "admin" in the **'job'** column.
- **EducationPunctuationCleaner** (`clean_education_punct`): Replace the period "." with a space " " in the **'education'** column (e.g., "basic.9y" → "basic 9y", "unknown." → "unknown "). This helps standardize values and correct input errors.
- Convert text to numeric values in the **'month'** and **'days_of_week'** columns.

In [ ]:
class JobAdminCleaner(BaseEstimator, TransformerMixin):
    def __init__(self, column='job'):
        self.column = column
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        X_transformed = X.copy()
        if self.column in X_transformed.columns:
            X_transformed.loc[:, self.column] = X_transformed[self.column].astype(str).replace('admin.', 'admin')
        else:
            warnings.warn(f"Warning: Column '{self.column}' not found. Skipping the JobAdminCleaner step.")
        return X_transformed

class EducationDotCleaner(BaseEstimator, TransformerMixin):
    def __init__(self, column='education'):
        self.column = column
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        X_transformed = X.copy()
        if self.column in X_transformed.columns:
            X_transformed.loc[:, self.column] = X_transformed[self.column].astype(str).str.replace('.', ' ', regex=False)
        else:
            warnings.warn(f"Warning: Column '{self.column}' not found. Skipping the EducationDotCleaner step.")
        return X_transformed

# --- Transformer for Mapping ---
class MappingTransformer(BaseEstimator, TransformerMixin):
    """
    Custom transformer to apply mapping based on a dictionary for a specific column.
    """
    def __init__(self, column, mapping):
        """
        Initialize transformer.
        Args:
            column (str): Name of the column to apply mapping.
            mapping (dict): Dictionary containing old:new value pairs.
        """
        self.column = column
        self.mapping = mapping

    def fit(self, X, y=None):
        """
        The fit method does nothing because the mapping is already provided.
        """
        return self

    def transform(self, X):
        """
        Apply mapping on the specified column.
        Args:
            X (pd.DataFrame): Input DataFrame.
        Returns:
            pd.DataFrame: Transformed DataFrame.
        """
        X_transformed = X.copy()
        if self.column in X_transformed.columns:
            # Apply map, values not in the mapping will be NaN
            # If a different handling is needed (e.g., retain old value or fill with default value),
            # the logic here needs to be adjusted.
            X_transformed.loc[:, self.column] = X_transformed[self.column].map(self.mapping)
            # Optional: Handle NaN if needed, e.g., fillna(-1) or another value
            # X_transformed[self.column] = X_transformed[self.column].fillna(-1) # Example
        else:
            warnings.warn(f"Warning: Column '{self.column}' not found. Skipping the MappingTransformer step.")

        return X_transformed

# --- Building Pipeline including mapping steps ---
cleaning_pipeline = Pipeline([
    ('clean_job_admin', JobAdminCleaner(column='job')),
    ('clean_education_dot', EducationDotCleaner(column='education')),
    # Add other steps if needed
])

# --- Apply Pipeline ---
df_cleaned = cleaning_pipeline.fit_transform(df)
# --- Check Results ---
print("\n--- Data after passing through the Pipeline ---")
print(df_cleaned)
print("\nUnique values in 'job' column after processing:", df_cleaned['job'].unique())
print("Unique values in 'education' column after processing:", df_cleaned['education'].unique())
print("Unique values in 'month' column after processing:", df_cleaned['month'].unique())
print("Unique values in 'day_of_week' column after processing:", df_cleaned['day_of_week'].unique())
print("\nData types of columns after processing:")
print(df_cleaned.dtypes) # Check the data types of month and day_of_week columns

--- Dữ liệu sau khi qua Pipeline ---
       age          job  marital            education  default housing loan  \
0       56    housemaid  married             basic 4y       no      no   no
1       57     services  married          high school  unknown      no   no
2       37     services  married          high school       no     yes   no
3       40        admin  married             basic 6y       no      no   no
4       56     services  married          high school       no      no  yes
...    ...          ...      ...                  ...      ...     ...  ...
41183   73      retired  married  professional course       no     yes   no
41184   46  blue-collar  married  professional course       no      no   no
41185   56      retired  married    university degree       no     yes   no
41186   44   technician  married  professional course       no      no   no
41187   74      retired  married  professional course       no     yes   no

         contact month day_of_week  campaign  pdays  previous     poutcome  \
0      telephone   may         mon         1    999         0  nonexistent
1      telephone   may         mon         1    999         0  nonexistent
2      telephone   may         mon         1    999         0  nonexistent
3      telephone   may         mon         1    999         0  nonexistent
4      telephone   may         mon         1    999         0  nonexistent
...          ...   ...         ...       ...    ...       ...          ...
41183   cellular   nov         fri         1    999         0  nonexistent
41184   cellular   nov         fri         1    999         0  nonexistent
41185   cellular   nov         fri         2    999         0  nonexistent
41186   cellular   nov         fri         1    999         0  nonexistent
41187   cellular   nov         fri         3    999         1      failure

       emp_var_rate  cons_price_idx  cons_conf_idx  euribor3m  nr_employed  \
0               1.1          93.994          -36.4      4.857       5191.0
1               1.1          93.994          -36.4      4.857       5191.0
2               1.1          93.994          -36.4      4.857       5191.0
3               1.1          93.994          -36.4      4.857       5191.0
4               1.1          93.994          -36.4      4.857       5191.0
...             ...             ...            ...        ...          ...
41183          -1.1          94.767          -50.8      1.028       4963.6
41184          -1.1          94.767          -50.8      1.028       4963.6
41185          -1.1          94.767          -50.8      1.028       4963.6
41186          -1.1          94.767          -50.8      1.028       4963.6
41187          -1.1          94.767          -50.8      1.028       4963.6

         y
0       no
1       no
2       no
3       no
4       no
...    ...
41183  yes
41184   no
41185   no
41186  yes
41187   no

[41176 rows x 20 columns]

Giá trị duy nhất cột 'job' sau khi xử lý: ['housemaid' 'services' 'admin' 'blue-collar' 'technician' 'retired'
 'management' 'unemployed' 'self-employed' 'unknown' 'entrepreneur'
 'student']
Giá trị duy nhất cột 'education' sau khi xử lý: ['basic 4y' 'high school' 'basic 6y' 'basic 9y' 'professional course'
 'unknown' 'university degree' 'illiterate']
Giá trị duy nhất cột 'month' sau khi xử lý: ['may' 'jun' 'jul' 'aug' 'oct' 'nov' 'dec' 'mar' 'apr' 'sep']
Giá trị duy nhất cột 'day_of_week' sau khi xử lý: ['mon' 'tue' 'wed' 'thu' 'fri']

Kiểu dữ liệu các cột sau khi xử lý:
age                 int64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
campaign            int64
pdays               int64
previous            int64
poutcome           object
emp_var_rate      float64
cons_price_idx    float64
cons_conf_idx     float64
euribor3m         float64
nr_employed       float64
y                  object
dtype: object

In [17]:
df_cleaned

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
0,56,housemaid,married,basic 4y,no,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high school,unknown,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high school,no,yes,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin,married,basic 6y,no,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high school,no,no,yes,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional course,no,yes,no,cellular,nov,fri,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional course,no,no,no,cellular,nov,fri,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university degree,no,yes,no,cellular,nov,fri,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional course,no,no,no,cellular,nov,fri,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional course,no,yes,no,cellular,nov,fri,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [18]:
df_cleaned['education'].unique()

array(['basic 4y', 'high school', 'basic 6y', 'basic 9y',
       'professional course', 'unknown', 'university degree',
       'illiterate'], dtype=object)

In [ ]:
class PdaysHandler(BaseEstimator, TransformerMixin):
    """
    Handle the value 999 in the 'pdays' column.
    1. Create a new binary column 'was_contacted_previously'.
    2. Replace the value 999 in the original 'pdays' column with NaN (or other values).
    """
    def __init__(self, pdays_col='pdays', new_col_suffix='_contacted_status', replace_999_with=np.nan):
        self.pdays_col = pdays_col
        self.new_col_name = f"{pdays_col}{new_col_suffix}"
        self.replace_999_with = replace_999_with

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X_transformed = X.copy()
        if self.pdays_col in X_transformed.columns:
            print(f"Processing column '{self.pdays_col}': Creating column '{self.new_col_name}' and replacing 999 with {self.replace_999_with}")

            # Step 1: Create a new column (before modifying the original column)
            X_transformed[self.new_col_name] = np.where(X_transformed[self.pdays_col] == 999, 0, 1)

            # Step 2: Explicitly convert the original pdays column to float before replacing
            # This addresses FutureWarning
            if pd.api.types.is_numeric_dtype(X_transformed[self.pdays_col]):  # Only convert if numeric
                X_transformed[self.pdays_col] = X_transformed[self.pdays_col].astype(float)
            else:
                # If it's not numeric, try to convert it to numeric, raise error if not possible
                try:
                    X_transformed[self.pdays_col] = pd.to_numeric(X_transformed[self.pdays_col], errors='raise').astype(float)
                except (ValueError, TypeError):
                    warnings.warn(f"Warning: Unable to convert column '{self.pdays_col}' to float. Skipping replacement of 999.")
                    return X_transformed  # Return without changing pdays if conversion fails

            # Step 3: Replace 999 with the desired value (now the type is compatible)
            X_transformed.loc[:, self.pdays_col] = X_transformed[self.pdays_col].replace(999.0, self.replace_999_with)  # Replace 999.0 (since it's now float)

        else:
            warnings.warn(f"Warning: Column '{self.pdays_col}' not found. Skipping the PdaysHandler step.")
        return X_transformed

# --- Run Step 5 again with the updated Transformer ---
# (Reuse df from Step 4)
print("\n--- Step 4 (Repeat): Handling 'pdays' column with the updated Transformer ---")
print("Values in the 'pdays' column before processing:\n", df[['pdays']].head())  # df here still has 'pdays' as int from the initial creation
pdays_handler_fixed = PdaysHandler(pdays_col='pdays', replace_999_with=np.nan)
df_cleaned = pdays_handler_fixed.fit_transform(df_cleaned)  # Create new df to see the difference
print("\nValues in the relevant columns after processing (updated):\n", df_cleaned[['pdays', 'pdays_contacted_status']].head())
print("Unique values in the 'pdays' column after processing (updated):", df_cleaned['pdays'].unique())
print("Unique values in the new 'pdays_contacted_status' column (updated):", df_cleaned['pdays_contacted_status'].unique())
print("Data type of 'pdays' column after processing (updated):", df_cleaned['pdays'].dtype)

--- Bước 4 (Lặp lại): Xử lý cột 'pdays' với Transformer đã sửa ---
Giá trị cột 'pdays' trước khi xử lý:
    pdays
0    999
1    999
2    999
3    999
4    999
Xử lý cột 'pdays': Tạo cột 'pdays_contacted_status' và thay thế 999 bằng nan

Giá trị các cột liên quan sau khi xử lý (đã sửa):
    pdays  pdays_contacted_status
0    NaN                       0
1    NaN                       0
2    NaN                       0
3    NaN                       0
4    NaN                       0
Giá trị duy nhất cột 'pdays' sau xử lý (đã sửa): [nan  6.  4.  3.  5.  1.  0. 10.  7.  8.  9. 11.  2. 12. 13. 14. 15. 16.
 21. 17. 18. 22. 25. 26. 19. 27. 20.]
Giá trị duy nhất cột 'pdays_contacted_status' mới (đã sửa): [0 1]
Kiểu dữ liệu cột 'pdays' sau xử lý (đã sửa): float64

In [20]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41176 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   age                     41176 non-null  int64
 1   job                     41176 non-null  object
 2   marital                 41176 non-null  object
 3   education               41176 non-null  object
 4   default                 41176 non-null  object
 5   housing                 41176 non-null  object
 6   loan                    41176 non-null  object
 7   contact                 41176 non-null  object
 8   month                   41176 non-null  object
 9   day_of_week             41176 non-null  object
 10  campaign                41176 non-null  int64
 11  pdays                   1515 non-null   float64
 12  previous                41176 non-null  int64
 13  poutcome                41176 non-null  object
 14  emp_var_rate            41176 non-null  float64
 15  cons_price_idx          41176 non-null  float64
 16  cons_conf_idx           41176 non-null  float64
 17  euribor3m               41176 non-null  float64
 18  nr_employed             41176 non-null  float64
 19  y                       41176 non-null  object
 20  pdays_contacted_status  41176 non-null  int32
dtypes: float64(6), int32(1), int64(3), object(11)
memory usage: 6.8+ MB

In [21]:
df_cleaned['pdays'].isnull().sum()

39661

In [22]:
df_cleaned.shape

(41176, 21)

In [23]:
df_cleaned.describe()

,age,campaign,pdays,previous,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,pdays_contacted_status
count,41176.00000,41176.000000,1515.000000,41176.000000,41176.000000,41176.000000,41176.000000,41176.000000,41176.000000,41176.000000
mean,40.02380,2.567879,6.014521,0.173013,0.081922,93.575720,-40.502863,3.621293,5167.034870,0.036793
std,10.42068,2.770318,3.824906,0.494964,1.570883,0.578839,4.627860,1.734437,72.251364,0.188256
min,17.00000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000,0.000000
25%,32.00000,1.000000,3.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000,0.000000
50%,38.00000,2.000000,6.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000,0.000000
75%,47.00000,3.000000,7.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000,0.000000
max,98.00000,56.000000,27.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000,1.000000

In [24]:
df_cleaned.dtypes.value_counts()

object     11
float64     6
int64       3
int32       1
dtype: int64

In [25]:
# Delete duplicated rows
df_cleaned.drop_duplicates(inplace=True)

# Generate a "clean data file"
df_cleaned.to_csv(artifact_name,index=False)

In [26]:
# Create a new artifact and configure with the necessary arguments
artifact = wandb.Artifact(name=artifact_name,
                          type=artifact_type,
                          description=artifact_description)
artifact.add_file(artifact_name)

In [27]:
# Upload the artifact to Wandb
run.log_artifact(artifact)

In [28]:
# close the run
# waiting a while after run the previous cell before execute this
run.finish()

VBox(children=(Label(value='4.339 MB of 4.339 MB uploaded (0.000 MB deduped)\r'), FloatProgress(value=1.0, max…

In [29]:
# #Export ra file CSV ---
# output_filename = 'data/bank_data_cleaned.csv'
# # index=False: Không lưu cột index của DataFrame vào file CSV
# # encoding='utf-8': Đảm bảo tương thích ký tự (thường là mặc định tốt)
# df_cleaned.to_csv(output_filename, index=False, encoding='utf-8')

# print(f"\nĐã lưu DataFrame cuối cùng vào file '{output_filename}'")

Đã lưu DataFrame cuối cùng vào file 'bank_data_cleaned.csv'